exclude: test_files/
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix --exit-non-zero-on-fix --force-exclude
        language: python
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        language: python
        types_or: [python, pyi]

      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        require_serial: true

      - id: pytest
        name: pytest
        entry: pytest --cov=flake8_future_annotations --cov-report=html --durations=0
        language: python
        types: [python]
        always_run: true
        pass_filenames: false
        verbose: true
